name: Python Tests

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'  # Замените на нужную версию Python

    - name: Install dependencies
      run: |
        pip install pytest  # Установите необходимые зависимости

    - name: Run tests
      run: |
        python test.py
